---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package:
    name: "{{ kibana_package }}"
    state: "{{ kibana_package_state }}"

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: "{{ kibana_service_state }}"
    enabled: "{{ kibana_service_enabled }}"

- name: Copy Kibana configuration.
  template:
<<<<<<< HEAD
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
=======
    src: "{{ kibana_config_template }}"
    dest: "{{ kibana_config_file_path }}"
>>>>>>> b307e5f37e21ea147c0bc3c1867325f131395faa
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
